name: test_env_pyqg
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - xarray
  - scipy
  - cython
  - pyfftw
  - pytest
  - future
  - delegate-property
  - pip:
    - codecov
    - pytest-cov
